# Generated by Django 4.1 on 2023-06-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('a', 'Average'), ('b', 'Bad'), ('e', 'Excellent')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
